= NASM 
:source-highlighter: rouge

* link:https://www.nasm.us/[Nasm]
* link:https://cs.lmu.edu/~ray/notes/nasmtutorial/[Nasm tutorial]

== Quick start

Folder `quickstart` contains a simple example with an assembler program and some tests. 
Program found max value between three numbers.

To compile assembler code and run tests, execute this command:

----
. run_quick_start.sh
----

Result should look like this:
----
Build program for file quickstart/maxofthree.test.c
==================
Run maxofthree.test
------------------
should_found_max_of_threehen_first_number: Ok
should_found_max_of_threehen_second_number: Ok
should_found_max_of_threehen_third_number: Ok
-------------
PASSED
-------------
Tests run: 3
Tests failed:0
----


Program is define in file `maxofthree.asm`. +
Tests are written in file `maxofthree.test.c`


You can find some projects in `examples` folder.

== How to

=== A minimal test file in C

File `minimal.test.c` is a trivial example of tests.
There is no library used. 
Everything is in the file.

It's just to show how it could work but it's too simple for a real usage. 

To launch it, execute: `. run_minimal.sh`

It just compile test file using `gcc` and run it.


=== Create a real test in C

Create a `.c` file like `simple.test.c`:

[source, c]
----
include::howto/simple.test.c[]
----

Script `run_simple.sh` compile and run tests.
Folder `test` is included as library.
It contains file defining functions to make tests.

[source, bash]
----
include::run_simple.sh[]
----

To write your own test, add all necessary includes in your test file.

Modify `gcc` command to add `.o` containing implementations used in your test.

`build_test_file` function in run_simple.sh, is used to replace key words (TEST and RUN_TESTS) by c code. 
A new file is generated in target folder.
You can open it to understand what is done.
This is this file that is compiled and executed. 

`RUN_TESTS` is replaced by a main function that call every function where `TEST` is first word in definition line.

=== Call assembler from a `c` file

To execute assembler in `.c` file, we have to add function definition in `.c` file (or in an `.h` file included in `.c` file).

Here is an example of a function definition to add in file:
`int maxofthree(int, int, int);`

Call this function like any other function in your program.

=== Run all tests in a file

To not have to enumarate all tests, we can use a script (test_generate.sh) to add main method with all tests.

Script read .c file and identify test by line starting by `TEST`.

All tests found are used to generate en main method to run them.
Main method is write before `RUN_TESTS()` text in .c file.

== Explain

=== Compile and run assembler

To compile an `asm` file and generate a `.o` file:
----
nasm -felf64 hello.asm
----

To link `.o` and generate a executable `a.out`:
----
ld hello.o
----

To run executable:
----
./a.out
----

It's possible to chain all commands:
----
nasm -felf64 hello.asm && ld hello.o && ./a.out
----

Output file can be define using `-o`:
----
nasm -felf64 hello.asm -o output.o
----

=== Run assembler from c file

With a file `.o` generated from an `asm` file, we can compile a `.c` file using it:
----
gcc callhello.c hello.o
----

A full command:
----
nasm -felf64 hello.asm && gcc callhello.c hello.o && ./a.out
----

== How to

=== Conitnuously testing

Go to your project folder and run following command to execute tests every 5 seconds.
---
while true; do . run.sh; date; sleep 5;  done
----

We display date only to view something changing in console.

To execute tests only when a file is modify, we can use `inotifywait`
----
while true; do inotifywait -q -r -e create,modify,delete .; . run.sh; date; done;
----

=== Nasm

* link:https://www.nasm.us/[]
* link:https://cs.lmu.edu/~ray/notes/nasmtutorial/[]
* link:https://asmtutor.com/[]
* link:http://www.lacl.fr/tan/asm[]
* link:https://benoit-m.developpez.com/assembleur/tutoriel/[]

In french:

* link:https://openclassrooms.com/fr/courses/2288321-apprenez-a-programmer-en-assembleur-x86/2288944-votre-premier-programme[]

=== inotifywait

link:https://makina-corpus.com/blog/metier/2013/utiliser-inotify-pour-tester-en-continu-son-code[]



////
== Tests

Just call:
. run.sh maxofthree


nasm -felf64 maxofthree.asm -o maxofthree.o && . generate_test.sh maxofthree && gcc progtest/maxofthree.test.c maxofthree.o -o test.out && ./test.out


nasm -felf64 maxofthree.asm -o maxofthree.o             \ # Generate maxofthree.o from assembler
. generate_test.sh maxofthree                           \ # Generate a c file from test file
gcc progtest/maxofthree.test.c maxofthree.o -o test.out \ # Compile test file linked with assembler.o
./test.out                                                # Run test

nasm -felf64 maxofthree.asm -o target/obj/maxofthree.o && . generate_test.sh maxofthree && gcc target/src/maxofthree.test.c target/obj/maxofthree.o -o target/objtest/maxofthree.out && ./target/maxofthree.out
----
 ////