= NASM 
:toc: left
:source-highlighter: rouge
Resources around assembler 


* link:https://www.nasm.us/[Nasm]
* link:https://cs.lmu.edu/~ray/notes/nasmtutorial/[Nasm tutorial]

== Quick start

Folder `quickstart` contains a simple example with an assembler program and some tests. 
Program found max value between three numbers.

To compile assembler code and run tests, execute this command:

----
. run_quick_start.sh
----

Result should look like this:
----
Build program for file quickstart/maxofthree.test.c
==================
Run maxofthree.test
------------------
should_found_max_of_threehen_first_number: Ok
should_found_max_of_threehen_second_number: Ok
should_found_max_of_threehen_third_number: Ok
-------------
PASSED
-------------
Tests run: 3
Tests failed:0
----


Program is define in file `maxofthree.asm`. +
Tests are written in file `maxofthree.test.c`


You can find some projects in `examples` folder.

== How to

=== A minimal test file in C

File `minimal.test.c` is a trivial example of tests.
There is no library used. 
Everything is in the file.

It's just to show how it could work but it's too simple for a real usage. 

To launch it, execute: `. run_minimal.sh`

It just compile test file using `gcc` and run it.


=== Create a real test in C

Create a `.c` file like `simple.test.c`:

[source, c]
----
include::howto/simple.test.c[]
----

Script `run_simple.sh` compile and run tests.
Folder `test` is included as library.
It contains file defining functions to make tests.

[source, bash]
----
include::run_simple.sh[]
----

To write your own test, add all necessary includes in your test file.

Modify `gcc` command to add `.o` containing implementations used in your test.

`build_test_file` function in run_simple.sh, is used to replace key words (TEST and RUN_TESTS) by `c` code. 
A new file is generated in target folder.
You can open it to understand what it does.
This is this file that is compiled and executed. 

`RUN_TESTS` is replaced by a main function that call every function where `TEST` is first word in definition line.

=== Call assembler from a `c` file

To execute assembler in `.c` file, we have to add function definition in `.c` file (or in an `.h` file included in `.c` file).

Here is an example of a function definition to add in file:
`int maxofthree(int, int, int);`

Call this function like any other function in your program.

=== Run all tests in a file

To not have to enumerate all tests, we can use a script (`test_generate.sh`) to add main method with all tests.

Script read `.c` file and identify test by line starting by `TEST`.

All tests found are used to generate a main method that run them.
Main method is write before `RUN_TESTS()` text in `.c` file.

== Explain

=== Compile and run assembler

To compile an `asm` file and generate a `.o` file:
----
nasm -felf64 hello.asm
----

To link `.o` and generate a executable `a.out`:
----
ld hello.o
----

To run executable:
----
./a.out
----

It's possible to chain all commands:
----
nasm -felf64 hello.asm && ld hello.o && ./a.out
----

Output file can be define using `-o`:
----
nasm -felf64 hello.asm -o output.o
----

=== Run assembler from c file

With a file `.o` generated from an `asm` file, we can compile a `.c` file using it:
----
gcc callhello.c hello.o
----

A full command:
----
nasm -felf64 hello.asm && gcc callhello.c hello.o && ./a.out
----

== How to

=== Continuously testing

Go to your project folder and run following command to execute tests every 5 seconds.
----
while true; do . run.sh; date; sleep 5;  done
----

We display date only to view something changing in console.

To execute tests only when a file is modify, we can use `inotifywait`
----
while true; do inotifywait -q -r -e create,modify,delete .; . run.sh; date; done;
----

=== Nasm

* link:https://www.nasm.us/[]
* link:https://cs.lmu.edu/~ray/notes/nasmtutorial/[]
* link:https://asmtutor.com/[]
* link:http://www.lacl.fr/tan/asm[]
* link:https://benoit-m.developpez.com/assembleur/tutoriel/[]
* link:https://fasterthanli.me/series/making-our-own-executable-packer/part-1[]
* link:https://filippo.io/linux-syscall-table/[Linux Syscall Table for x86 64]
* link:https://github.com/las-nish/NASM-Assembly-Collection/blob/main/README.md

In french:

* link:https://openclassrooms.com/fr/courses/2288321-apprenez-a-programmer-en-assembleur-x86/2288944-votre-premier-programme[]
* link:https://leria-info.univ-angers.fr/~jeanmichel.richer/assembly/Programmation_Assembleur_x86_32_et_64_bits_sous_Linux_Ubuntu.pdf[]
* link:https://www.unilim.fr/pages_perso/tristan.vaccon/cours_nasm.pdf[Programmation Assembleur NASM - Résumé]
* link:https://ruuand.github.io/Assembleur/

=== Disasemble

.For a 64-bit code
----
ndisasm -b 64 [FILE].o
ndisasm -b 64  [FILE].so
----

To see memory map:
----
gdb [FILE]
(gdb) starti
(gdb) info proc
----

We will see the process ID (`process [PID]`)
Then, we can call in an other terminal 
`pmap [PID]`
or
`cat /proc/[PID]/maps

=== Debug

see: https://redirect.cs.umbc.edu/portal/help/nasm/nasm.shtml[]

----
gdb [PRGRAM NAME]
break main
run
set disassembly-flavor intel
----

.To see code and execution pointer
----
disassemble main
----

[%collapsible]
.Result
====
----
Dump of assembler code for function main:
   0x0000000000401126 <+0>:     endbr64 
   0x000000000040112a <+4>:     push   rbp
   0x000000000040112b <+5>:     mov    rbp,rsp
=> 0x000000000040112e <+8>:     sub    rsp,0x20
   0x0000000000401132 <+12>:    mov    DWORD PTR [rbp-0x14],edi
   0x0000000000401135 <+15>:    mov    QWORD PTR [rbp-0x20],rsi
   0x0000000000401139 <+19>:    mov    edi,0x7
   0x000000000040113e <+24>:    call   0x401170 <add_5>
   0x0000000000401143 <+29>:    mov    DWORD PTR [rbp-0x4],eax
   0x0000000000401146 <+32>:    mov    eax,DWORD PTR [rbp-0x4]
   0x0000000000401149 <+35>:    mov    esi,eax
   0x000000000040114b <+37>:    lea    rax,[rip+0xeb2]        # 0x402004
   0x0000000000401152 <+44>:    mov    rdi,rax
   0x0000000000401155 <+47>:    mov    eax,0x0
   0x000000000040115a <+52>:    call   0x401030 <printf@plt>
   0x000000000040115f <+57>:    mov    eax,0x0
   0x0000000000401164 <+62>:    leave  
----
====


.See registers
----
info registers
----

.Go to the next instruction
----
nexti
----

=== inotifywait

link:https://makina-corpus.com/blog/metier/2013/utiliser-inotify-pour-tester-en-continu-son-code[]


=== Syscall

link:https://blog.rchapman.org/posts/Linux_System_Call_Table_for_x86_64/[Linux System Call Table for x86 64]

=== CPU Architecture 

Use command
----
lscpu | grep "Architecture:"
----

=== Cycle time

https://stackoverflow.com/questions/54621381/rdtscp-in-nasm-always-returns-the-same-value-timing-a-single-instruction

rdtsc

https://medium.com/geekculture/rdtsc-the-only-way-to-benchmark-fc84562ef734
http://meseec.ce.rit.edu/eecc250-winter99/250-1-24-2000.pdf

////
== Tests

Just call:
. run.sh maxofthree


nasm -felf64 maxofthree.asm -o maxofthree.o && . generate_test.sh maxofthree && gcc progtest/maxofthree.test.c maxofthree.o -o test.out && ./test.out


nasm -felf64 maxofthree.asm -o maxofthree.o             \ # Generate maxofthree.o from assembler
. generate_test.sh maxofthree                           \ # Generate a c file from test file
gcc progtest/maxofthree.test.c maxofthree.o -o test.out \ # Compile test file linked with assembler.o
./test.out                                                # Run test

nasm -felf64 maxofthree.asm -o target/obj/maxofthree.o && . generate_test.sh maxofthree && gcc target/src/maxofthree.test.c target/obj/maxofthree.o -o target/objtest/maxofthree.out && ./target/maxofthree.out
----
 ////